daemon:
  intervalMs: 2000
  logLevel: info

sensors:
  source: 'systeminformation' # lm-sensors/sysfs support will be added in the future

drivers:
  - id: 'llw-aio'
    type: 'lianli-wireless'
    method: 'usb'
    macs:
      - 'AA:BB:CC:DD:EE:01'  # receiver MAC for the AIO cluster
    role: 'aio'

  - id: 'llw-front-top'
    type: 'lianli-wireless'
    method: 'usb'
    macs:
      - 'AA:BB:CC:DD:EE:02'  # receiver MAC for top-front intake
    role: 'front-top'

  - id: 'llw-front-bottom'
    type: 'lianli-wireless'
    method: 'usb'
    macs:
      - 'AA:BB:CC:DD:EE:03'  # receiver MAC for bottom-front intake
    role: 'front-bottom'

activeProfile: 'default'

profiles:
  default:
    clusters:
      aio:
        curve:
          source: 'cpu'
          curve:
            - tempC: 30
              pwmPercent: 40
            - tempC: 50
              pwmPercent: 60
            - tempC: 70
              pwmPercent: 85
            - tempC: 80
              pwmPercent: 100
        lighting:
          mode: 'effect'
          effect: 'rainbow'
          brightness: 200

      front-top:
        curve:
          source: 'cpu'
          curve:
            - tempC: 30
              pwmPercent: 30
            - tempC: 50
              pwmPercent: 50
            - tempC: 70
              pwmPercent: 80
            - tempC: 80
              pwmPercent: 100
        lighting:
          mode: 'effect'
          effect: 'rainbow'
          brightness: 200

      front-bottom:
        curve:
          source: 'cpu'
          curve:
            - tempC: 30
              pwmPercent: 30
            - tempC: 50
              pwmPercent: 50
            - tempC: 70
              pwmPercent: 80
            - tempC: 80
              pwmPercent: 100
        lighting:
          mode: 'effect'
          effect: 'rainbow'
          brightness: 200